# 1. Numpy

- 파이썬 라이브러리 중 하나 -> 과학연산
- 배열 -> 행렬 (선형대수)
- 선형대수,  푸리에 변환 -> 수학 함수

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3, 4]) # 1차원 배열 생성

In [ ]:
print(a) # []안에 ,가 없기때문에 1차원 배열이다

[1 2 3 4]


In [ ]:
l =[1, 2, 3, 4]
print(l)

[1, 2, 3, 4]


In [ ]:
print(a.shape)

(4,)


In [ ]:
print(a.ndim) # 몇 차원인지 묻는 코드

1


In [ ]:
print(a.dtype) # 배열의 데이터 타입을 묻는 코드

int64


In [ ]:
print(a.itemsize) # 각 요소의 바이트 단위 크기

8


In [ ]:
b = np.array([[1, 2],[3, 4], [5, 6]]) # 2차원 배열

print(b)

[[1 2]
 [3 4]]


In [ ]:
print(b)
print(b.ndim)
print(b.dtype)
print(b.itemsize)
print(b.nbytes)

[[1 2]
 [3 4]]
2
int64
8
32


In [ ]:
# 3차원

c = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]]])

print(c)
print(c.ndim)
print(c.dtype)
print(c.itemsize)
print(c.nbytes)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]
3
int64
8
64


In [ ]:
# 하나의 숫자값: 스칼라

s = np.array(1)
print(s)

1


In [ ]:
# 1차원: 벡터

v = np.array([1, 2, 3,])
print(v)

[1 2 3]


In [ ]:
# 2차원: 행렬(Matrix)

m = np.array([[1, 2, 3], [1, 2, 3]])
print(m)

[[1 2 3]
 [1 2 3]]


In [ ]:
# 3차원: 텐서(Tensor)

t = np.array([[[1, 2], [1, 2]], [[1, 2], [1, 2]]])
print(t)

[[[1 2]
  [1 2]]

 [[1 2]
  [1 2]]]


In [ ]:
# for 을 이용해서 배열 생성

f = np.array([i for i in range(0, 10, 2)]) # (start, end, step)

In [ ]:
print(f)

[0 2 4 6 8]


In [ ]:
print(f)
print(f.ndim)
print(f.dtype)
print(f.itemsize)
print(f.nbytes)

[0 2 4 6 8]
1
int64
8
40


## 데이터 타입

1. 숫자형
2. 문자형
3. 논리형

### 숫자형

- 부호가 있는 정수(Signed interger)
- 부호가 없는 정수(Unsigned interger)
- 실수(floating point)
- 복소수(complex)

In [ ]:
# int (8bit, 16bit, 32bit, 64bit)

data = [1.1, 2, 3]

i = np.array(data, dtype=np.int32)
print(i)

[1 2 3]


In [ ]:
print(i.dtype)

int32


In [ ]:
data2 = [-1, 2, 3]

ui = np.array(data2, dtype=np.uint32) # uint 8, 16, 32(0 ~4,294,967,295), 64
print(ui)

[4294967295          2          3]


In [ ]:
f = np.array(data, dtype=np.float64)

print(f)

[1.1 2.  3. ]


In [ ]:
c =np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype=np.complex64)

In [ ]:
print(c.real) # 실수
print(c.imag) # 허수

[1. 3. 5.]
[2. 4. 6.]


## 문자형

- string_
- unicod_


In [ ]:
data = [1, 2, 3]

s = np.string_(data)
print(s)

b'\x01\x02\x03'


In [ ]:
print(s.dtype) # S3: string 3

|S3


In [ ]:
data3 = [1, 2, 3, 4, 5]

# string_
s2 = np.string_(data3) # s2 = np.array(data3, dtype='S')
# print, 그 자체, 데이터 타입
print(s2)
print(s2.dtype)

b'\x01\x02\x03\x04\x05'
|S5


In [ ]:
u = np.array(data3, dtype='U') # unicode

print(u)
print(u.dtype)

['1' '2' '3' '4' '5']
<U1


In [ ]:
data4 = ([11, 22, 33, 44])

u2 = np.array(data4, dtype='U')
print(u2)

['11' '22' '33' '44']


In [ ]:
print(u2.dtype)

<U2


## 논리형 (boolean)

- True(1), False(0)
- 비트 연산 사용 : & and, | or, ^ xor, ~ not

In [ ]:
l1 = np.array([True, False, True])
l2 = np.array([False, True, False])

print(l1.dtype)
print(l2.dtype)

bool
bool


In [ ]:
and_ = np.logical_and(l1, l2)
print(and_)

[False False False]


## 데이터 형 변환 (Cast, Casting)

- 데이터들끼리 형태를 맞춰주기 위해 사용한다.
- 각각의 데이터들 마다 형태가 다르기에...
- 예시) 이미지 데이터 -> uint형 으로 불러옴 -> float

In [ ]:
# 방법 1

data = [1.1, 2, 3]

a = np.float64(data) # np.테이터타입

print(a)
print(a.dtype)

[1.1 2.  3. ]
float64


In [ ]:
# 방법 2

a = a.astype(np.int64)

print(a)
print(a.dtype)

[1 2 3]
int64


In [ ]:
b = np.uint16(0)

print(b)
print(b.dtype)

0
uint16


In [ ]:
b = b - 1

print(b)
print(b.dtype) # 부호가 생기면서 연산해야해서 컴퓨터가 알아서 바꿨다

-1
int64


In [ ]:
c = np.uint16(-1) # uint16 (0 ~ 65,535)
print(c)

65535


## 산술연산

In [ ]:
import time

data = [[1, 2, 3], [4, 5, 6]]
data2 = [[1, 1, 1], [2, 2, 2]]

start_time = time.time()

for i in range(len(data)):
    for j in range(len()):

In [ ]:
data = [[1, 2, 3], [4, 5, 6]]

In [ ]:
sum = 0

for i in range(len(data)):
    for j in range(len(data[0])):
        sum += data[i][j]

print(sum)

21


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 사칙연산
sum = a + b
min = a - b
mul = a * b
div = a / b

print(sum)
print(min)
print(mul)
print(div)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

aa = np.exp(a) # 자연로그
print(aa)

[ 2.71828183  7.3890561  20.08553692]


In [ ]:
bb = np.log(b) # 자연로그
print(bb)

[1.38629436 1.60943791 1.79175947]


In [ ]:
cc = np.log2(b) # 밑이 2인 로그
print(cc)

[2.         2.32192809 2.5849625 ]


In [ ]:
d = np.array([0, np.pi/2, np.pi]) # 삼각함수

sin_ = np.sin(d)

cos_ = np.cos(d)

tan_ = np.tan(d)

print(sin_)
print(cos_)
print(tan_)

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


## 배열의 연결과 분할

In [ ]:
print("a" + "b")

ab


In [ ]:
x = [1, 2, 3]
y = [4, 5, 6]

In [ ]:
concat = np.concatenate([x, y])
print(concat)

[1 2 3 4 5 6]


In [ ]:
x2 = [[1, 2], [3, 4]] # 2x2
y2 = [[4, 5], [6, 7]] # 2x2

concat2 = np.concatenate([x2, y2], axis=1)
concat3 = np.concatenate([x2, y2], axis=0)
print(concat2)
print(concat3)

[[1 2 4 5]
 [3 4 6 7]]
[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [ ]:
print(x2)

[[1, 2], [3, 4]]


In [ ]:
arr =  np.arange(10) # 0 ~ n-1
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
arr.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
x2 = [[1, 2], [3, 4]] # 2x2
y2 = [[4, 5], [6, 7]] # 2x2

# hstack horizontal - 수평 열 방향
h = np.hstack([x2, y2])
print(h)

[[1 2 4 5]
 [3 4 6 7]]


In [ ]:
# vstack vertical - 수직 행 방향 
v = np.vstack([x2, y2])
print(v)

[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [ ]:
x2 = np.array([[1, 2], [3, 4], [5, 6]]) # 3x2

# hsplit
h2 = np.hsplit(x2, 2)
print(h2)
# array([[1], [3], [5]]), array([[2], [4], [6]])

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]])]


In [ ]:
x2 = np.array([[1, 2], [3, 4], [5, 6]]) # 3x2

# vsplit

v2 = np.vsplit(x2, 3)
print(v2)

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]


## 다양한 배열 만들기

In [ ]:
zero = np.zeros([3, 4])  # 영 행렬은 항등식 만들 때 사용한다.

In [ ]:
print(zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
one = np.ones([3, 4])
print(one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
eye = np.eye(3)  # 단위 행렬
print(eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Numpy 제공 함수

In [ ]:
arr1 = np.array([-1, -2, -3, -4])  
abs_arr = np.abs(arr1) # abs 절댓값 함수

print(abs_arr)

[1 2 3 4]


In [ ]:
arr2 = np.array([1, 4, 9, 16])
sqrt_arr = np.sqrt(arr2) # sqrt 제곱근 함수

print(sqrt_arr)

[1. 2. 3. 4.]


## 집계함수

In [ ]:
a = np.array([1, 2, 3, 4, 5])
a_mean = np.mean(a) # mean 평균값 함수

print(a_mean)

3.0


In [ ]:
b = np.array([1, 3, 5, 7, 9])
b_median = np.median(b) # median 중앙값 함수

print(b_median)

5.0


In [ ]:
c = np.array([1, 2, 3, 4, 5])
c_std = np.std(c) # std 표준편차 함수

print(c_std)

1.4142135623730951


In [ ]:
d = np.array([1, 2, 3, 4, 5])
d_var = np.var(d) # var 분산 함수

print(d_var)

2.0


In [ ]:
d_sum = np.sum(d) # sum 합계 함수

print(d_sum)

15


In [ ]:
d_cumsum = np.cumsum(d) # cumsum 누적합계 함수

print(d_cumsum) # 배열 형태로 반환된다.

[ 1  3  6 10 15]


In [ ]:
d_min = np.argmin(d) '''인덱스의 최솟값 함수'''

print(d_min)

0


In [ ]:
d_min = np.min(d) # 배열의 최솟값 함수

print(d_min)

1


In [ ]:
d_max = np.argmax(d) '''인덱스의 최댓값 함수'''

print(d_max)

4


In [ ]:
a = np.array([0, 0, 0, 1])

a_true = np.any(a) # any는 배열 안에, 하나라도 True면 True
print(a_true)

True


In [ ]:
a_all = np.all(a) # all는 배열 안에, 모두 True여야 True
print(a_all) 

False


In [ ]:
# Nan
a = np.array([1, 2, np.nan, 4]) # nan이 있으면 nansum 함수를 사용해야 한다
a_nsum = np.nansum(a)

print(a_nsum)

7.0


In [ ]:
a_sum = np.sum(a)
print(a_sum)

nan


In [ ]:
d = np.array([1, 2, 3, 4, 5]) 

condition = np.where(d < 3, d, 0)  # 조건 함수
condition1 = np.where(d < 3)      

print(condition)  # 배열형태
print(condition1) # 튜플형태

[1 2 0 0 0]
(array([0, 1]),)


### Boolean Indexing

조건에 따른 요소들을 판별해서 새로운 배열을 만든다.

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) # 원본데이터는 건들지 않는다.

even_a = a[a % 2 == 0] # 짝수를 의미
print(even_a)
print(a)

[ 2  4  6  8 10]
[ 1  2  3  4  5  6  7  8  9 10]


### Broadcast(브로드캐스트)

- 배열간 연산을 할 때 크기와 규격이 맞아야 하는데,
- 크기가 다른 배열 간의 연산도 가능하게 해줌.
- ex) 1차원, 2차원 간 연산.

In [ ]:
# ex)

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b
print(c)

[5 7 9]


In [ ]:
d = np.array([[1], [2], [3]])
e = np.array([4, 5, 6])

f = d + e
print(f)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


- 두 배열의 차원수가 다를경우, 더 작은 차원의 배열을 큰 차원의 배열과 맞을 때까지 차원수 1을 추가한다.
- 두 배열의 차원 수가 같을 경우에도, 크기가 1인 차원이 있다면 다른 배열의 크기가 일치하도록 복제된다.
- 두 배열의 차원 수가 같은 경우에도, 모든 차원의 크기가 같거나 크기가 1이라면 모양이 같은 두 배열의 요소 간 연산을 한다.

In [ ]:
d = np.array([[1], [2], [3]]) # 3x1
e = np.array([[4], [5], [6]]) # 3x1

f = d + e
print(f)

[[5]
 [7]
 [9]]


In [ ]:
d = np.array([[1], [2], [3]]) # 3x1
e = np.array([[4, 5, 6]])     # 1x3

f = d + e
print(f)

[[5 6 7]
 [6 7 8]
 [7 8 9]]
