In [2]:
import numpy as np

### 1. array()
차원별 배열 생성

In [3]:
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)

[1 2 3 4 5]


In [4]:
arr_1d = np.array([i for i in range(1,10, 2)])
print(arr_1d)

[1 3 5 7 9]


In [5]:
print(np.array(range(10)))
print(np.array(range(1, 11)))
print(np.array(range(2, 11, 2)))
print(np.array(range(10, 2, -1)))

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10]
[10  9  8  7  6  5  4  3]


In [6]:
arr_1d = np.array([1, 2, 3, 4, 5],dtype='f')
print(arr_1d)

[1. 2. 3. 4. 5.]


In [7]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [8]:
arr_2d = np.array(range(1,13, 2)).reshape(2,3)
print(arr_2d)

[[ 1  3  5]
 [ 7  9 11]]


In [ ]:
# Error : 요소의 개수가 reshape의 행렬 개수에 맞게 설정해야 합니다.
arr_2d = np.array(range(1,13, 2)).reshape(2,4)
print(arr_2d)

ValueError: ignored

In [ ]:
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### 2. arange()

In [ ]:
print(np.array(range(10)))
print(np.array(range(1, 11)))
print(np.array(range(2, 11, 2)))
print(np.array(range(2, 11, 0.5)))
print(np.array(range(10, 2, -1)))
print(np.array(range(10, 2, -0.5)))

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10]


TypeError: ignored

In [ ]:
print(np.arange(10))
print(np.arange(1, 11))
print(np.arange(2, 11, 2))
print(np.arange(2, 11, .5))
print(np.arange(10, 2, -1))
print(np.arange(10, 2, -.5))

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10]
[ 2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5  8.   8.5
  9.   9.5 10.  10.5]
[10  9  8  7  6  5  4  3]
[10.   9.5  9.   8.5  8.   7.5  7.   6.5  6.   5.5  5.   4.5  4.   3.5
  3.   2.5]


### 3. 다양한 배열 만들기


In [ ]:
# 일차원으로 변경
arr_3d.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# 0으로 채워진 배열 생성
z = np.zeros((2,2))
z

array([[0., 0.],
       [0., 0.]])

In [ ]:
# 1로 채워진 배열 생성
one1 = np.ones((2,2))
one1

array([[1., 1.],
       [1., 1.]])

In [ ]:
# 내가 원하는 값으로 채워진 배열 생성
f = np.full((2,2),10)
f

array([[10, 10],
       [10, 10]])

In [ ]:
# 단위행렬
e = np.eye(3)
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 4. 넘파이 함수를 이용해서 문제풀기


4.1 주어진 여러 개의 1차원 배열을 연결하여 하나의 큰 1차원 배열로 반환하세요.

In [10]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9, 10])

# concat 함수

In [11]:
concat = np.concatenate([arr1, arr2, arr3])
print(concat)

[ 1  2  3  4  5  6  7  8  9 10]


4.2 주어진 2차원 배열에서 각 열의 평균값을 계산하여 새로운 1차원 배열로 나타내세요.

In [12]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# mean() 함수 응용하기

In [13]:
means = np.mean(arr, axis = 0)
print(means)

[4. 5. 6.]


4.3 주어진 2차원 배열에서 각 행의 최대값을 구하여 1차원 배열로 반환하세요.

In [ ]:
# np.max()

In [16]:
max = np.max(arr, axis = 1)

print(max)

[3 6 9]


4.4 0에서 1사이의 값으로 크기 10개의 1차원 배열을 만들어주세요.

In [ ]:
# linspace()

In [18]:
linspace = np.linspace(0, 1, 10)

print(linspace)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


4.5 주어진 1차원 배열에서 짝수인 요소들의 합을 계산하는 함수 sum_of_evens를 작성하세요.

- 
def sum_of_evens(arr: np.ndarray) -> int:


In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

def sum_of_evens(arr: np.ndarray) -> int:
    evens = arr[arr % 2 == 0]
    return np.sum(evens)
    
print(sum_of_evens(arr))

30


4.6 수평분할, 수직분할, 수평 스택, 수직 스택 문제를 풀어봅시다.

In [23]:
# 분할할 배열 생성
arr = np.arange(1, 13).reshape((3, 4))
print("원본 배열:")
print(arr)

원본 배열:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [29]:
# 1. 수평분할하기 -> 다시 원본으로 스택쌓기
harr = np.hsplit(arr, 2)
print("수평분할 :")
print(harr)

arr_1 = harr[0]
arr_2 = harr[1]
harr2 = np.hstack([arr_1, arr_2])
print("다시 원본 :")
print(harr2)

# 2. 수직분할하기 -> 다시 원본으로 스택쌓기
varr = np.vsplit(arr, 3)
print("수직분할 :")
print(varr)

arr_3 = varr[0]
arr_4 = varr[1]
arr_5 = varr[2]
varr2 = np.vstack([arr_3, arr_4, arr_5])
print("다시 원본 :")
print(varr2)


수평분할 :
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]
다시 원본 :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
수직분할 :
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]
다시 원본 :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


4.7 배열에서 조건에 맞는 값 반환하는 문제를 풀어봅시다.

In [30]:
# 조건 : 값을 10으로 나누었을 때 나머지가 0이면 원래 값 출력, 아니면 0으로 출력하세요.
arr = np.arange(0, 100, 5).reshape((5,4))
print(np.where(arr % 10 == 0, arr, 0))

[[ 0  0 10  0]
 [20  0 30  0]
 [40  0 50  0]
 [60  0 70  0]
 [80  0 90  0]]


4.8 [3x3]배열 lst 중 짝수만 뽑아내는 부울린 인덱싱 배열(numpy 배열)을 사용하여 짝수 배열 n 을 만드시오

In [31]:
lst = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
a = np.array(lst)

In [36]:
even_a = a[a % 2 == 0] # 짝수를 의미
print(even_a)

[2 4 6 8]


4.9 각도를 이용해서 삼각함수를 만들어봅시다.

In [37]:
angle = np.pi / 3 # 라디안 표기 = 60도 
# 360도는 2라디안 으로, 180도는 1라디안으로 표현합니다.

angle

1.0471975511965976

In [38]:
# 사인 함수 계산
sin_ = np.sin(angle)
print("사인 값:", sin_)

# 코사인 함수 계산
cos_ = np.cos(angle)
print("코사인 값:", cos_)

# 탄젠트 함수 계산
tan_ = np.tan(angle)
print("탄젠트 값:", tan_)

사인 값: 0.8660254037844386
코사인 값: 0.5000000000000001
탄젠트 값: 1.7320508075688767


4.10 조건함수를 사용해서  짝수조건을 만족하는 요소의 값이 2배로 만드는 배열을 만드시오.

In [40]:
arr = np.array([1, 2, 3, 4, 5])

In [41]:
condition = np.where(arr % 2 == 0, arr * 2, arr)

print(condition)

[1 4 3 8 5]


In [ ]:
# 4.1 정답
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9, 10])
np.concatenate([arr1,arr2,arr3])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# 4.2 정답

np.mean(arr, axis=0) 


In [ ]:
# 4.3 정답

np.max(arr, axis=1)

array([3, 6, 9])

In [ ]:
# 4.4 정답
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
# 4.5 정답

def sum_of_evens(arr: np.ndarray) -> int:
    evens = arr[arr % 2 == 0]  # 짝수인 요소 선택
    return np.sum(evens)  # 짝수인 요소들의 합 반환

In [ ]:
# 4.6 정답
arr_split = np.hsplit(arr, 2)
print("수평 분할 결과:")
print(arr_split)

arr_1 = arr_split[0]
arr_2 = arr_split[1]
arr_stack = np.hstack((arr_1, arr_2))
print(arr_stack)

수평 분할 결과:
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# 수직 분할
arr_split = np.vsplit(arr, 3)
print("수직 분할 결과:")
print(arr_split)

arr_1 = arr_split[0]
arr_2 = arr_split[1]
arr_3 = arr_split[2]
arr_stack = np.vstack((arr_1, arr_2, arr_3))
print(arr_stack)

수직 분할 결과:
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# 4.7 정답
# 조건 : 값을 10으로 나누었을 때 나머지가 0이면 원래 값 출력, 아니면 0으로 출력하세요.
arr = np.arange(0, 100, 5).reshape((5,4))
print(np.where(arr%10==0, arr,0))

[[ 0  0 10  0]
 [20  0 30  0]
 [40  0 50  0]
 [60  0 70  0]
 [80  0 90  0]]


In [33]:
# 4.8 정답

# 3가지 정답이 있습니다. 인덱싱 배열을 이용하기
bool_indexing_array = np.array([
    [False,  True, False],
    [True, False,  True],
    [False,  True, False]
])
 
n = a[bool_indexing_array];
print(n)    

[2 4 6 8]


In [34]:
# 배열 a 에 대해 짝수면 True, 홀수면 False 
bool_indexing = (a % 2 == 0)
print(bool_indexing)
print(a[bool_indexing])

[[False  True False]
 [ True False  True]
 [False  True False]]
[2 4 6 8]


In [35]:
# 간단한 조건으로 호출하기
n = a[ a % 2 == 0 ]
n

array([2, 4, 6, 8])

In [ ]:
# 4.9 정답이
# 사인 함수 계산
sin_value = np.sin(angle)
print("사인 값:", sin_value)

# 코사인 함수 계산
cos_value = np.cos(angle)
print("코사인 값:", cos_value)

# 탄젠트 함수 계산
tan_value = np.tan(angle)
print("탄젠트 값:", tan_value)

사인 값: 0.8660254037844386
코사인 값: 0.5000000000000001
탄젠트 값: 1.7320508075688767


In [ ]:
# 4.10 정답
new_arr = np.where(arr % 2 == 0, arr * 2, arr)
print("조건을 만족하는 요소를 2배로:", new_arr)

조건을 만족하는 요소를 2배로: [1 4 3 8 5]
