브로드 캐스팅
- 두 배열 간 차원의 크기가 같다 -> 그냥 계산
- 두 배열 간 차원의 크기가 다르고, 한 배열의 차원이 1차원(벡터)
- **차원을 늘렸을 때 계산이 가능한 경우!**

### 난수 생성 함수

Random
* 랜덤한 값을 뽑아줄 때 사용.
* 가짜값을 이용해 예제를 생성해 실습해볼 때 사용한다.

In [ ]:
import numpy as np

In [ ]:
a = np.random.rand(2, 2) # rand는 0과 1사이의 랜덤값 생성
print(a)

[[0.28707913 0.15323905]
 [0.04306072 0.02312007]]


In [ ]:
b = np.random.randn(2, 2) # randn는 평균이 0, 분산이 1: 표준 정규분포 값 이내에서 랜덤값 생성
print(b)

[[ 1.29491662 -0.360521  ]
 [-0.66408915 -0.55765453]]


In [ ]:
c = np.random.randint(0, 10, size=5) # 랜덤한 정수값 생성
print(c)

[6 9 3 4 9]


In [ ]:
c2 = np.random.randint(0, 10, size=(2, 2)) # 랜덤한 정수값 생성
print(c2)

[[0 1]
 [5 4]]


In [ ]:
d = np.arange(10) # 0 ~ 9 까지 값을 생성
np.random.shuffle(d) #복사본 생성이 안된다. 원본 값이 변한다.
print(d)

[2 1 0 7 3 8 6 4 9 5]


In [ ]:
choice = np.random.choice(d, 5) # 중복을 허용한다.
print(choice)

[3 8 2 4 2]


In [ ]:
choice = np.random.choice(d, 5, replace=False) # 중복을 허용하지 않는다.
print(choice)

[8 1 7 6 5]


In [ ]:
choice = np.random.choice(d, 5, p=[0.1, 0, 0.3, 0.2, 0.1, 0, 0.1, 0.1, 0.1, 0]) # 지정확률 랜덤함수
# p가 100%(1)가 되어야한다
print(choice)

[0 6 4 2 7]


In [ ]:
# permutation 순열
a = np.arange(10)
a_p = np.random.permutation(a) 
print(a_p)
print(a) # 원본 바뀌지 않는다

[4 6 8 0 2 1 5 7 3 9]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# 정규분포를 따르는 난수 생성
# a = np.random.normal('평균', '표준편차', '갯수')
a = np.random.normal(0, 1, 3)
print(a)

[-0.21807856  1.63469429  0.42947503]
